name: md_to_pdf
version: "0.2"
author: GeorgyFirsov <gfirsov007@gmail.com>
about: Converts a markdown formatted file into pretty pdf
args:
    - input:
        short: i
        long: input
        help: Path to the input file
        takes_value: true
        value_name: markdown file
    - output:
        short: o
        long: output
        help: Path to the output file to be created
        takes_value: true
        value_name: PDF file